GET http://localhost:3000/user

###

GET http://localhost:3000/user/63ea41945e038ac4a817538d

###

POST http://localhost:3000/user/register
Content-Type: application/json

{
    "username": "linda",
    "password": "1234"
}

###


POST http://localhost:3000/user/logIn
Content-Type: application/json

{
    "username": "sara",
    "password": "1234"
}

###


POST http://localhost:3000/user/logOut

###